// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktsxgvvyqcnngzworiut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0c3hndnZ5cWNubmd6d29yaXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0MTM2MTAsImV4cCI6MjA4Nzk4OTYxMH0.DWHhFkoDfMrfoYHSqJTv0mLKx-wmdhBlDwjJR714uTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});