// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mphcxawsimtwcuizrgpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1waGN4YXdzaW10d2N1aXpyZ3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzcyODgsImV4cCI6MjA2OTYxMzI4OH0.LkUxV2KqHaGVGi_vutPNJgxxv1_Zpjo_pcagxFgruAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});